In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
credit_df = pd.read_csv("../data/processed/credit_cleaned.csv")

credit_df.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,male,2,own,Unknown,little,1169,6,radio/TV,good
1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,49,male,1,own,little,Unknown,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad

In [3]:
credit_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1000 non-null   int64
 1   Sex               1000 non-null   str
 2   Job               1000 non-null   int64
 3   Housing           1000 non-null   str
 4   Saving accounts   1000 non-null   str
 5   Checking account  1000 non-null   str
 6   Credit amount     1000 non-null   int64
 7   Duration          1000 non-null   int64
 8   Purpose           1000 non-null   str
 9   Risk              1000 non-null   str
dtypes: int64(4), str(6)
memory usage: 111.0 KB

In [4]:
numerical_columns = credit_df.select_dtypes(include=["int64", "float64"]).columns

categorical_columns = credit_df.select_dtypes(include=["object"]).columns

C:\Users\khanr\AppData\Local\Temp\ipykernel_16008\3776390945.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = credit_df.select_dtypes(include=["object"]).columns

In [5]:
print("Numerical Columns")
print(numerical_columns)

print()

print("Categorical Columns")
print(categorical_columns)

Numerical Columns
Index(['Age', 'Job', 'Credit amount', 'Duration'], dtype='str')

Categorical Columns
Index(['Sex', 'Housing', 'Saving accounts', 'Checking account', 'Purpose',
       'Risk'],
      dtype='str')

In [6]:
credit_df["Risk"] = credit_df["Risk"].map({
    "good": 0,
    "bad": 1
})

In [7]:
credit_df["Risk"].value_counts()

Risk
0    700
1    300
Name: count, dtype: int64

In [8]:
le = LabelEncoder()

In [9]:
for col in categorical_columns:
    if col != "Risk":
        credit_df[col] = le.fit_transform(credit_df[col])

In [10]:
credit_df.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,1,2,1,0,1,1169,6,5,0
1,22,0,2,1,1,2,5951,48,5,1
2,49,1,1,1,1,0,2096,12,3,0
3,45,1,2,0,1,1,7882,42,4,0
4,53,1,2,0,1,1,4870,24,1,1

In [12]:
credit_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1000 non-null   int64
 1   Sex               1000 non-null   int64
 2   Job               1000 non-null   int64
 3   Housing           1000 non-null   int64
 4   Saving accounts   1000 non-null   int64
 5   Checking account  1000 non-null   int64
 6   Credit amount     1000 non-null   int64
 7   Duration          1000 non-null   int64
 8   Purpose           1000 non-null   int64
 9   Risk              1000 non-null   int64
dtypes: int64(10)
memory usage: 78.3 KB

In [13]:
X = credit_df.drop(columns="Risk")

X.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,67,1,2,1,0,1,1169,6,5
1,22,0,2,1,1,2,5951,48,5
2,49,1,1,1,1,0,2096,12,3
3,45,1,2,0,1,1,7882,42,4
4,53,1,2,0,1,1,4870,24,1

In [14]:
y = credit_df["Risk"]

y.head()

0    0
1    1
2    0
3    0
4    1
Name: Risk, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [16]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Target :", y_train.shape)
print("Testing Target  :", y_test.shape)

Training Features : (800, 9)
Testing Features  : (200, 9)

Training Target : (800,)
Testing Target  : (200,)

In [17]:
scaler = StandardScaler()

In [18]:
X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [19]:
print(X_train_scaled[:5])

[[ 1.05778394  0.67223926  0.14597546 -2.01876206 -1.23679163  0.
   1.92576638  1.28959203 -0.9272846 ]
 [ 0.24244893  0.67223926  0.14597546 -0.13646643 -0.21570463 -1.0439915
  -0.89285257 -0.74259502  1.11350682]
 [-0.66347887  0.67223926  0.14597546 -0.13646643 -0.21570463  0.
   0.81643342  1.28959203  0.60330897]
 [-0.57288609 -1.4875656  -2.96816777 -0.13646643 -1.23679163  1.0439915
   0.29956809  1.28959203 -0.41708675]
 [-1.02584999 -1.4875656   0.14597546 -0.13646643 -1.23679163  1.0439915
   1.98265525  2.30568556 -0.9272846 ]]